# ⚙️ Cấu hình REST API
[api]
enable = true
swagger = true
address = "tcp://0.0.0.0:1317"

# ⚙️ Cấu hình gRPC
[grpc]
enable = true
address = "0.0.0.0:9090"

# ⚙️ Cấu hình gRPC-Web (nếu frontend cần)
[grpc-web]
enable = true
address = "0.0.0.0:9091"

# ⚙️ Cấu hình mức phí tối thiểu để chấp nhận giao dịch
# Đặt đúng vị trí theo Cosmos SDK >=0.47 (trong section [app] hoặc đầu file, không nằm ngoài section)
[app]
pruning = "default"

# ⚙️ Cấu hình snapshot (để state sync nhanh hơn)
[snapshot]
interval = 1000
keep_recent = 2

# ⚙️ Cấu hình telemetry (Prometheus)
[telemetry]
enabled = false
prometheus-retention-time = 0
