# Configuration settings for the EduChain application

[app]
name = "EduChain"
version = "1.0.0"
description = "A decentralized education platform"

[database]
type = "sqlite"
connection_string = "educhain.db"

[logging]
level = "info"
file = "educhain.log"

[network]
port = 8080
host = "0.0.0.0"

[security]
enable_ssl = false
private_key_path = "path/to/private/key.pem"
public_key_path = "path/to/public/key.pem"