# Tên node hiển thị trong mạng
moniker = "node1"

# Địa chỉ RPC để truy vấn trạng thái node
[rpc]
laddr = "tcp://0.0.0.0:26657"

# Cấu hình P2P
[p2p]
laddr = "tcp://0.0.0.0:26656"
external_address = "tcp://<public-ip>:26656"  # Nếu có IP công khai
persistent_peers = ""                         # Sẽ được sinh tự động
seeds = ""                                    # Có thể dùng seed node nếu muốn

# Cấu hình thời gian block
consensus.timeout_commit = "1s"
consensus.timeout_propose = "1s"

# Cấu hình log
log_level = "info"

# Cấu hình node key
node_key_file = "config/node_key.json"
priv_validator_key_file = "config/priv_validator_key.json"
